### ISSUE TITLE
Add ability to set global label for every metrics from clusterwide config in Cartridge role (metrics.yml)

### ISSUE THREAD

**Issue by no1seman** [tarantool/metrics#259]
It could be useful to add custom global labels to metrics.

Proposed configuration format:

```yml
metrics:
    export:
    - path: "/metrics/json"
       format: "json"
    - path: "/metrics/prom"
       format: "prometheus"
    global-labels:
          label-name1: value1
          label-name2: value2
```
