### ISSUE TITLE
roles: metrics role for cartridge

### ISSUE THREAD

**Issue by ZolotarevIgor-mail-ru** [tarantool/metrics#73]
According to: https://github.com/tarantool/cartridge/pull/873 

proposed configuration format:
```
metrics:
      export:
        - path: "/metrics/json"
          format: "json"
        - path: "/metrics/prom"
          format: "prometheus"
```
where
* `metrics` is a top level section name
* `export` is exporter configuration, e.g. [1] is a way to enable json metrics via http endpoint /metrics/json
Default metrics and global label 'alias' enable by default after init().
