### ISSUE TITLE
Declare metrics cartridge role as permanent

### ISSUE THREAD

**Issue by olegrok** [tarantool/metrics#82]
If I enable this role in my init.lua I agree that my metrics will be enabled on ALL instances. It could be really strange to enable metrics per replicaset.

So I propose:
  - Declare metrics role as permanent (I believe it's literally could be redundant in long roles list)

**Comment by ZolotarevIgor-mail-ru** [comment]
You can reconfigure `/metrics` endpoint with config:
```yaml
metrics:
  export:
    - path: '/mymetrics'
      format: 'json'
```
